/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        // Deep-space agri palette: near-black greens + neon mint accents
        night: "#060A08",
        surface: "#101412",
        raised: "#181D1A",
        // Stitch design tokens (chat UI)
        primary: "#4EDEA3",
        "primary-fixed": "#6FFBBE",
        "primary-fixed-dim": "#4EDEA3",
        "primary-container": "#10B981",
        "on-primary": "#003824",
        "on-primary-fixed": "#002113",
        background: "#0B0F0D",
        "surface-container": "#1C211E",
        "surface-container-low": "#181D1A",
        "surface-container-lowest": "#0B0F0D",
        "surface-container-high": "#262B28",
        "surface-container-highest": "#313633",
        "on-surface": "#DFE4DF",
        "on-surface-variant": "#BBCABF",
        "outline-variant": "#3C4A42",
        outline: "#86948A",
        error: "#FFB4AB",
        secondary: "#62DCAD",
        "secondary-fixed": "#80F9C8",
        tertiary: "#FFB95F",
        "surface-dim": "#101412",
        "secondary-fixed-dim": "#62DCAD",
        "tertiary-fixed": "#FFDDB8",
        tertiary: "#FFB95F",
        "tertiary-container": "#E29100",
        "on-secondary": "#003827",
        "on-secondary-fixed": "#002115",
        "on-secondary-fixed-variant": "#00513A",
        "on-secondary-container": "#003121",
        "on-tertiary": "#472A00",
        "on-tertiary-fixed": "#2A1700",
        "on-tertiary-fixed-variant": "#653E00",
        "on-tertiary-container": "#523200",
        "surface-bright": "#353A37",
        "surface-variant": "#313633",
        "surface-tint": "#4EDEA3",
        "inverse-surface": "#DFE4DF",
        "inverse-on-surface": "#2D312F",
        "inverse-primary": "#006C49",
        "error-container": "#93000A",
        "on-error": "#690005",
        "on-error-container": "#FFDAD6",
        forest: {
          50: "#131C16",
          100: "#18241C",
          200: "#203026",
          300: "#2B4433",
          400: "#34D399",
          500: "#10B981",
          600: "#0A8F63",
          700: "#2EC98A",
          800: "#159A67",
          900: "#0A1F15",
          950: "#06130D",
        },
        // Semantic tokens repurposed for dark theme (used across all pages)
        cream: "#0E1712",
        ink: "#E6F0E9",
        clay: "#8AA394",
        mint: "#5EEAD4",
      },
      fontFamily: {
        sans: [
          "Inter",
          "system-ui",
          "-apple-system",
          "Segoe UI",
          "Roboto",
          "sans-serif",
        ],
        display: [
          "Space Grotesk",
          "Inter",
          "system-ui",
          "sans-serif",
        ],
        mono: [
          "JetBrains Mono",
          "ui-monospace",
          "Consolas",
          "monospace",
        ],
        // Stitch typography roles
        "headline-lg": ["Space Grotesk", "Inter", "sans-serif"],
        "headline-md": ["Space Grotesk", "Inter", "sans-serif"],
        "display-hero": ["Space Grotesk", "Inter", "sans-serif"],
        "body-md": ["Inter", "system-ui", "sans-serif"],
        "body-lg": ["Inter", "system-ui", "sans-serif"],
        "label-mono": ["JetBrains Mono", "ui-monospace", "monospace"],
        "data-lg": ["JetBrains Mono", "ui-monospace", "monospace"],
      },
      fontSize: {
        "headline-lg": ["32px", { lineHeight: "40px", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "data-lg": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "label-mono": [
          "12px",
          { lineHeight: "16px", letterSpacing: "0.1em", fontWeight: "500" },
        ],
        "display-hero": [
          "48px",
          { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" },
        ],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
      },
      spacing: {
        "container-padding": "24px",
        "card-gap": "20px",
      },
      boxShadow: {
        card: "0 1px 0 rgba(255,255,255,0.04) inset, 0 8px 32px rgba(0,0,0,0.45)",
        lift: "0 2px 0 rgba(255,255,255,0.05) inset, 0 20px 60px rgba(0,0,0,0.6)",
        glow: "0 0 24px rgba(52,211,153,0.35), 0 0 64px rgba(52,211,153,0.12)",
        "glow-sm": "0 0 12px rgba(52,211,153,0.3)",
      },
      backgroundImage: {
        "grid-faint":
          "linear-gradient(rgba(94,234,212,0.045) 1px, transparent 1px), linear-gradient(90deg, rgba(94,234,212,0.045) 1px, transparent 1px)",
        "hero-radial":
          "radial-gradient(ellipse 80% 55% at 50% -10%, rgba(16,185,129,0.22), transparent)",
        "mint-gradient": "linear-gradient(135deg, #6EE7B7 0%, #10B981 100%)",
      },
      keyframes: {
        "fade-up": {
          "0%": { opacity: "0", transform: "translateY(10px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        "pulse-soft": {
          "0%, 100%": { opacity: "1" },
          "50%": { opacity: "0.45" },
        },
        shimmer: {
          "0%": { backgroundPosition: "-200% 0" },
          "100%": { backgroundPosition: "200% 0" },
        },
        float: {
          "0%, 100%": { transform: "translateY(0)" },
          "50%": { transform: "translateY(-8px)" },
        },
        scan: {
          "0%": { transform: "translateX(-100%)" },
          "100%": { transform: "translateX(220%)" },
        },
      },
      animation: {
        "fade-up": "fade-up 0.45s ease-out both",
        "pulse-soft": "pulse-soft 1.6s ease-in-out infinite",
        shimmer: "shimmer 2.4s linear infinite",
        float: "float 5s ease-in-out infinite",
        scan: "scan 2.8s ease-in-out infinite",
      },
    },
  },
  plugins: [],
};
