services:
  db:
    image: mysql:8.4
    container_name: Unnati-db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: Unnati
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - "3306:3306"
    volumes:
      - Unnati_mysqldata:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-ppassword"]
      interval: 5s
      timeout: 3s
      retries: 20

volumes:
  Unnati_mysqldata:
