"""LLM integration via any OpenAI-compatible API (OpenRouter by default).

The LLM NEVER performs calculations. It receives validated facts and returns:
  - a structured farmer-friendly explanation, or
  - structured extraction of crop/quantity/location/harvest from free text.

Every call is guarded: disabled config, network failure, timeout, or invalid
output falls back to deterministic content. The demo must never break.
"""

from __future__ import annotations

import json
import logging
import re
from typing import Any

import httpx
from pydantic import BaseModel, ValidationError

from app.core.config import settings
from app.schemas.recommendation import LLMExplanation

logger = logging.getLogger("Unnati.llm")


class ExtractedFields(BaseModel):
    crop: str | None = None
    quantity_kg: float | None = None
    location_text: str | None = None
    harvest_hint: str | None = None


EXPLANATION_SYSTEM_PROMPT = """You are Unnati's agricultural logistics explanation assistant.

Your job is to explain a recommendation generated by deterministic software.

You MUST:
- use only the supplied facts;
- preserve all supplied numbers;
- explain the recommendation simply;
- clearly identify estimates;
- mention when data is demo/seeded;
- explain urgency when spoilage risk is relevant;
- avoid technical terminology where possible;
- never invent prices, trucks, farmers, routes or weather;
- never change profit values, quantities or capacity constraints.

You MUST NOT:
- perform alternative calculations;
- create unsupported claims;
- claim that seeded prices are live;
- claim spoilage is guaranteed;
- make financial guarantees.

If a fact is unavailable, say it is unavailable.
Respond with JSON only, using this exact shape:
{
  "headline": string,
  "summary": string,
  "why_this_option": [string],
  "action": string,
  "urgency": string,
  "warnings": [string]
}"""

EXTRACTION_SYSTEM_PROMPT = """You extract structured farm-produce details from a
farmer's message (which may be English, Hinglish, or Hindi written in
Devanagari script).

Return JSON only:
{"crop": string|null, "quantity_kg": number|null, "location_text": string|null, "harvest_hint": string|null}

Rules:
- crop: single crop word as written (e.g. "tomato", "tamatar", "potato").
- quantity_kg: numeric kilograms; convert quintals to kg (1 quintal = 100 kg); convert tonnes to kg (1 tonne = 1000 kg).
- location_text: village/town/area name if mentioned.
- harvest_hint: when the produce was or will be harvested ("this morning", "kal", "in 3 days").
Extract only what the message actually says; use null for anything not stated."""


def llm_available() -> bool:
    return bool(settings.LLM_ENABLED and settings.LLM_API_KEY)


def _chat_completion(system: str, user: str) -> str | None:
    """Call an OpenAI-compatible chat completions endpoint. Returns text or None."""
    if not llm_available():
        return None
    url = settings.LLM_BASE_URL.rstrip("/") + "/chat/completions"
    headers = {
        "Authorization": f"Bearer {settings.LLM_API_KEY}",
        "Content-Type": "application/json",
    }
    payload = {
        "model": settings.LLM_MODEL,
        "temperature": settings.LLM_TEMPERATURE,
        "messages": [
            {"role": "system", "content": system},
            {"role": "user", "content": user},
        ],
    }
    try:
        response = httpx.post(
            url, headers=headers, json=payload, timeout=settings.LLM_TIMEOUT_SECONDS
        )
        response.raise_for_status()
        data = response.json()
        content = data["choices"][0]["message"]["content"]
        return str(content)
    except Exception as exc:  # noqa: BLE001 - deliberate broad fallback
        logger.warning("LLM call failed, falling back: %s", type(exc).__name__)
        return None


def _parse_json_block(text: str | None) -> dict[str, Any] | None:
    if not text:
        return None
    # Tolerate markdown fences around the JSON payload.
    match = re.search(r"\{.*\}", text, re.DOTALL)
    if not match:
        return None
    try:
        parsed = json.loads(match.group(0))
        return parsed if isinstance(parsed, dict) else None
    except json.JSONDecodeError:
        return None


def build_fallback_explanation(facts: dict[str, Any]) -> LLMExplanation:
    """Deterministic explanation used whenever the LLM is unavailable."""
    rec_mandi = facts.get("recommended_mandi", "the recommended mandi")
    baseline_mandi = facts.get("baseline_mandi", "your nearest mandi")
    gain = facts.get("net_gain", 0)
    truck = facts.get("truck", "")
    pool_count = facts.get("pool_farmer_count", 1)
    spoilage_level = facts.get("spoilage_risk", "")
    hours_remaining = facts.get("hours_remaining")
    warnings = ["Mandi prices are seeded demo values."]

    why = [
        f"{rec_mandi} gives you the highest expected net return after transport "
        f"and estimated spoilage.",
    ]
    if facts.get("is_return_trip"):
        why.append(f"Truck {truck} is already returning toward your region, so its spare "
                   "capacity costs less than booking a dedicated trip.")
    if pool_count > 1:
        why.append(f"Pooling with {pool_count - 1} nearby farmer(s) reduces your share of the transport cost.")

    urgency = ""
    if spoilage_level in ("MEDIUM", "HIGH", "CRITICAL") and hours_remaining is not None:
        urgency = (
            f"Your estimated spoilage window is about {int(hours_remaining)} hours — "
            "move the load before it closes."
        )
    elif spoilage_level:
        urgency = f"Estimated spoilage risk is {spoilage_level}."

    headline = (
        f"Sell at {rec_mandi}"
        + (f" with truck {truck}" if truck else "")
        + (f" along with {pool_count - 1} nearby farmer(s)" if pool_count > 1 else "")
        + "."
    )

    return LLMExplanation(
        headline=headline,
        summary=(
            f"Compared with selling at {baseline_mandi}, this option is expected to earn "
            f"you about \u20b9{gain:,.0f} more."
        ),
        why_this_option=why,
        action=(f"Join truck {truck} before departure." if truck else "Confirm your load."),
        urgency=urgency or "No urgency detected for this load.",
        warnings=warnings,
    )


def explain_recommendation(facts: dict[str, Any]) -> tuple[LLMExplanation, bool]:
    """Returns (explanation, llm_was_used). Never raises."""
    user_payload = json.dumps(facts, ensure_ascii=False, default=str)
    raw = _chat_completion(EXPLANATION_SYSTEM_PROMPT, user_payload)
    parsed = _parse_json_block(raw)
    if parsed is not None:
        try:
            return LLMExplanation.model_validate(parsed), True
        except ValidationError:
            logger.warning("LLM explanation failed schema validation; using fallback.")
    return build_fallback_explanation(facts), False


def extract_fields(text: str) -> ExtractedFields:
    """LLM extraction with graceful failure (caller applies rule fallback)."""
    raw = _chat_completion(EXTRACTION_SYSTEM_PROMPT, text)
    parsed = _parse_json_block(raw)
    if parsed is None:
        return ExtractedFields()
    try:
        extracted = ExtractedFields.model_validate(parsed)
    except ValidationError:
        return ExtractedFields()
    # Basic sanitation of numeric output.
    if extracted.quantity_kg is not None and (
        extracted.quantity_kg <= 0 or extracted.quantity_kg > 500_000
    ):
        extracted.quantity_kg = None
    for field_name in ("crop", "location_text", "harvest_hint"):
        value = getattr(extracted, field_name)
        if value is not None:
            cleaned = str(value).strip()[:80]
            setattr(extracted, field_name, cleaned or None)
    return extracted


LANGUAGE_NAMES = {"en": "simple English", "hi": "simple conversational Hindi (Devanagari script)"}

CHAT_REPLY_SYSTEM_PROMPT_TEMPLATE = """You are Unnati, a warm WhatsApp-style assistant helping
a farmer who has just received a load recommendation computed by deterministic software.

Write ONE short WhatsApp message (max ~120 words) presenting the facts below.
You MUST:
- respond in {language};
- use ONLY the supplied facts;
- preserve every number, price, truck id and mandi name exactly as given;
- keep it friendly and simple for a farmer (short sentences, a few emojis);
- mention that prices are demo values.

You MUST NOT:
- perform any calculations or create new numbers;
- invent trucks, farmers, mandis, routes or options;
- give financial guarantees.

Return plain message text only — no JSON, no code fences."""


def chat_reply(facts: dict[str, Any], language: str) -> str | None:
    """Natural-language chat presentation of validated facts. Returns None to
    signal fallback to the deterministic template."""
    system_prompt = CHAT_REPLY_SYSTEM_PROMPT_TEMPLATE.format(
        language=LANGUAGE_NAMES.get(language, LANGUAGE_NAMES["en"])
    )
    raw = _chat_completion(
        system_prompt, json.dumps(facts, ensure_ascii=False, default=str)
    )
    if not raw:
        return None
    text = raw.strip().strip("`").strip()
    # Basic sanitation: reject absurd lengths or empty output.
    if not text or len(text) > 2500 or len(text) < 10:
        return None
    return text
